### ISSUE TITLE
N4BiasFieldCorrection

### ISSUE THREAD

**Issue by raihaan** [CobraLab/quarantine#2]
the command N4BiasFieldCorrection currently functions differently on scinet than it does locally.

On scinet (: N4BiasFieldCorrection -d 3 -b [200] -c [100x100x100x100,0.0000000001] -i $tmp/input.nii -o $tmp/output.nii  

Locally: the script only functions without the "-d" option,

patrai@cicws25:/data/chamal/projects/raihaan/defaced$ N4BiasFieldCorrection -d 3 -b [200] -c [100x100x100x100,0.0000000001] -i test.nii -o n4test.nii
Unsupported dimension

without -2,
patrai@cicws25:/data/chamal/projects/raihaan/defaced$ N4BiasFieldCorrection 3 -b [200] -c [100x100x100x100,0.0000000001] -i test.nii -o n4test.nii
Mask not read.  Creating Otsu mask.
Current level = 1
  Iteration 1 (of 100).   Current convergence value = 0.000867379 (threshold = 1e-10)
...
.,..
running running

bit of googling suggests this may mean we have an old version of the N4BiasFieldCorrection script
http://ehc.ac/p/advants/discussion/840261/thread/8145343e/

**Comment by egarza** [comment]
Hi guys, 
I actually got this error, so it's good to know.

I'm using Matt's version for the N4 correction, but I will give a try the other one you mention here. 

Thanks

Ed

**Comment by egarza** [comment]
By the way, this is Matt's version in case you don't have it:

#!/bin/bash
#
# usage:
#      register <input.mnc> <output.mnc>
#   
input=$1
output=$2

tmp=/tmp/N4minc_$$
mkdir $tmp

mnc2nii -signed -short $input $tmp/input.nii
N4BiasFieldCorrection -d 3 -b [200] -c [100x100x100x100,0.0000000001] -i $tmp/input.nii -o $tmp/output$
nii2mnc $tmp/output.nii $output

rm -r $tmp

**Comment by gdevenyi** [comment]
See minc-bpipe-toolkit for a implementation more similar to how the MNI runs N3.

I think I've figured out how to get bpipe working on scinet, implementation details as soon as I test it out.

**Comment by egarza** [comment]
Awesome, thanks.

bpipe is going to be sweet when it works.

**Comment by gdevenyi** [comment]
Well..it does work. Just not on scinet yet. :-)

**Comment by egarza** [comment]
I'm sure we will all be swimming in bpipe soon

El Wednesday, April 29, 2015, Gabriel A. Devenyi <notifications@github.com>
escribió:

> Well..it does work. Just not on scinet yet. :-)
> On Apr 29, 2015 10:59 PM, "Eduardo Garza" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Awesome, thanks.
> >
> > bpipe is going to be sweet when it works.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/CobraLab/quarantine/issues/2#issuecomment-97644498>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CobraLab/quarantine/issues/2#issuecomment-97659778>.
>


-- 
Eduardo A. Garza Villarreal, M.D., Ph.D.


   - Investigador, *Subdirección de Investigaciones Clínicas, Instituto
   Nacional de Psiquiatría.*
   - Catedrático, *Consejo Nacional de Ciencia y Tecnología (CONACYT).*
   - Investigador Asociado, *Center of Functionally Integrative
   Neuroscience, Universidad de Aarhus, Dinamarca.*
