### ISSUE TITLE
Push latest minc-toolkit changes

### ISSUE THREAD

**Issue by josephdviviano** [CobraLab/quarantine#25]
Hey @gdevenyi ,

We've been having some trouble with our minc-toolkit install here due to unmet dependencies in the .deb file distributed (I know you are already aware of this).

I'd like to build a new minc-toolkit module here and I'm pretty sure from what I've seen on Scinet that you have more up-to-date modules available on your system. Would you be willing to share them with us?

Thanks,

**Comment by gdevenyi** [comment]
Oh god this is gonna be a mess :)

It will take me a little bit to clean up and commit my quarantine changes, but I will. If I don't do it by next week, poke me again.

**Comment by josephdviviano** [comment]
Thanks so much Gabe! We really appreciate you sharing all of your hard work :)

**Comment by josephdviviano** [comment]
Totally forgot about this! How's this coming along? I forget why we needed minc-toolkit, but I thought I would check in anyhow.

**Comment by gdevenyi** [comment]
I've pushed all the modules, build scripts will be coming....

**Comment by josephdviviano** [comment]
OK, thanks again.

**Comment by josephdviviano** [comment]
This is no longer an urgent issue on our end, so I'm going to close this.
